version: 2.1
jobs:
  lint:
    docker:
      - image: rosiney/mkdkr
    parallelism: 2
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: lint commit
        command: make lint.commit
    - run:
        name: lint shellcheck
        command: make lint.shellcheck
  test:
    docker:
      - image: rosiney/mkdkr
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: test unit
        command: make test.unit
  build:
    docker:
      - image: rosiney/mkdkr
    parallelism: 4
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: examples simple
        command: make examples.simple
    - run:
        name: examples service
        command: make examples.service
    - run:
        name: examples dind
        command: make examples.dind
    - run:
        name: examples escapes
        command: make examples.escapes
    - run:
        name: examples stdout
        command: make examples.stdout
    - run:
        name: examples shell
        command: make examples.shell
    - run:
        name: examples pipeline
        command: make examples.pipeline
